---
- name: Check mandatory variables are defined
  ansible.builtin.assert:
    that:
      - pve_api_token_secret
      - pve_api_token_id
      - pve_api_password
      - pve_guest_password
    success_msg: VALUES ARE set
    fail_msg: VALUE is not set.  Create a vault-encrypted value

- name: Install proxmoxer
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-proxmoxer
    - libguestfs-tools
- name: Add pve-template main
  ansible.builtin.include_tasks:
    file: pve_template_{{ 'interactive' if (pve_template_interactive | bool) else 'automated' }}.yml

- name: Run preinstall tasks
  ansible.builtin.include_tasks:
    file: pve_template_preinstall.yml
