---
- name: Run tasks against proxmox template_builder host
  when:
    - inventory_hostname in groups['template_builder']
  block:
    - name: Check mandatory variables are defined
      ansible.builtin.assert:
        that:
          - pve_api_token_secret
          - pve_api_token_id
          - pve_api_password
          - pve_guest_password
        success_msg: VALUES ARE set
        fail_msg: VALUE is not set.  Create a vault-encrypted value

    - name: Add pve-template main
      ansible.builtin.include_tasks:
        file: pve_template_{{ 'interactive' if (pve_template_interactive | bool) else 'automated' }}.yml

    - name: Run preinstall tasks
      ansible.builtin.include_tasks:
        file: pve_template_preinstall.yml

- name: Include base roles on template_tmp guest
  ansible.builtin.include_role:
    name: "{{ item }}"
  loop:
    - common
    - ceph-fs
    - rsyslog
  when:
    - inventory_hostname in groups['template_tmp']

- name: Run post-installation tasks
  ansible.builtin.include_role:
    name: proxmox
    tasks_from: pve_template_postinstall.yml
  when:
    - inventory_hostname in groups['template_builder']
