---
# defaults file for ansible-pve-template
pve_api_host: proxmox-api.local
pve_node: proxmox-pve
pve_api_user: root@pam
pve_api_token_id: "{{ vault_pve_api_token_id | mandatory }}"
pve_api_token_secret: "{{ vault_pve_api_token_secret | mandatory }}"
pve_api_password: "{{ vault_pve_api_password | mandatory }}"
pve_template_temporary_vm_cidr: 10.0.10.10/24
pve_template_vm_storage_default_size: 15
pve_template_ci_user: root
pve_guest_password: "{{ vault_pve_guest_password | mandatory }}"
pve_template_template_basedir: /mnt/pve/cephfs/template
pve_template_iso_directory: "{{ pve_template_template_basedir }}/iso"
pve_template_lxc_directory: "{{ pve_template_template_basedir }}/cache"
pve_template_ci_ssh_keys: {}
pve_template_cloud_images:
  rocky9:
    dist_name: Rocky
    dist_release: 9
    dist_checksum: sha256:{{ lookup('ansible.builtin.url', 'https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud.latest.x86_64.qcow2.CHECKSUM')
      | regex_search('[a-f|0-9]{64}') }}
    dist_arch: x86_64
    dist_url: https://dl.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud.latest.x86_64.qcow2
    lxc_url: http://download.proxmox.com/images/system/rockylinux-9-default_20221109_amd64.tar.xz
  almalinux9:
    dist_name: AlmaLinux
    dist_release: 9
    dist_checksum: sha256:https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/CHECKSUM
    dist_arch: x86_64
    dist_url: https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/AlmaLinux-9-GenericCloud-latest.x86_64.qcow2
    lxc_url: http://download.proxmox.com/images/system/almalinux-9-default_20221108_amd64.tar.xz
  centos9:
    dist_name: CentOS
    dist_release: 9-Stream
    dist_checksum: sha256:{{ lookup('ansible.builtin.url', 'https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2.SHA256SUM')
      | regex_search('[a-f|0-9]{64}') }}
    dist_arch: x86_64
    dist_url: https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
    lxc_url: http://download.proxmox.com/images/system/centos-9-stream-default_20221109_amd64.tar.xz
  ubuntu2204:
    dist_name: Ubuntu
    dist_release: 22.04
    dist_checksum: sha256:https://cloud-images.ubuntu.com/releases/22.04/release/SHA256SUMS
    dist_arch: x86_64
    dist_url: https://cloud-images.ubuntu.com/releases/22.04/release/ubuntu-22.04-server-cloudimg-amd64.img
    lxc_url: http://download.proxmox.com/images/system/ubuntu-22.04-standard_22.04-1_amd64.tar.zst
  ubuntu2404:
    dist_name: Ubuntu
    dist_release: 24.04
    dist_checksum: sha256:https://cloud-images.ubuntu.com/releases/24.04/release/SHA256SUMS
    dist_arch: x86_64
    dist_url: https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img
    lxc_url: http://download.proxmox.com/images/system/ubuntu-24.04-standard_24.04-2_amd64.tar.zst

pve_template_lxc_ssh_pubkey: ""

# vault_pve_api_token_secret:
# vault_pve_api_token_id:
# vault_pve_api_password:
# vault_pve_guest_password:
